packages:
  - "playgrounds/*"
  - "client"
  - "docs"

overrides:
  "@nuxt/fonts": workspace:*
  "@nuxt/kit": 4.2.2
  "@nuxt/schema": 4.2.2
  "@types/node": ^24.13.1
  "@unocss/core": ^66.7.0
  "@unocss/nuxt": ^66.7.0
  "@unocss/preset-attributify": ^66.7.0
  "@unocss/preset-icons": ^66.7.0
  "@unocss/preset-mini": ^66.7.0
  "@unocss/reset": ^66.7.0
  nuxt: 4.2.2
  typescript: ^6.0.3
  unocss: ^66.7.0
  vite: ~7.3.5

patchedDependencies:
  "@nuxt/devtools-ui-kit": patches/@nuxt__devtools-ui-kit.patch

allowBuilds:
  "@parcel/watcher": false
  "@tailwindcss/oxide": true
  better-sqlite3: true
  esbuild: false
  sharp: true
  unrs-resolver: false
  vue-demi: false
