name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-review:
    uses: nuxt/.github/.github/workflows/dependency-review.yml@38c61022708adef2a1dc350b00e05c6b6ac7665a # main
    with:
      fail-on-provenance-change: true
