name: release

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Cut a prerelease instead of a normal release, e.g. `beta`, `rc`, or `0`'
        required: false
        default: ''

permissions: {}

jobs:
  pr:
    if: |
      github.repository_owner == 'nuxt'
      && !github.event.repository.fork
      && (
        (
          github.event_name == 'push'
          && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        ) || (
          github.event_name == 'workflow_dispatch'
          && !startsWith(github.ref, 'refs/tags/')
        )
      )
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: danielroe/uppt/pr@775bb233d2c5671b2c12d48f822778aae8231376 # v0.6.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ inputs.prerelease }}

  release:
    if: |
      github.event_name == 'pull_request'
      && github.event.pull_request.merged == true
      && startsWith(github.event.pull_request.head.ref, 'release/v')
      && github.event.pull_request.head.repo.full_name == github.repository
      && !github.event.repository.fork
    runs-on: ubuntu-latest
    concurrency:
      group: release-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    permissions:
      contents: write
      actions: write
    steps:
      - uses: danielroe/uppt/release@775bb233d2c5671b2c12d48f822778aae8231376 # v0.6.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  pack:
    if: github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    concurrency:
      group: pack-${{ github.ref }}
      cancel-in-progress: false
    permissions: {}
    outputs:
      files: ${{ steps.pack.outputs.files }}
    steps:
      - id: pack
        uses: danielroe/uppt/pack@775bb233d2c5671b2c12d48f822778aae8231376 # v0.6.7

  publish:
    if: |
      github.event_name == 'workflow_dispatch'
      && startsWith(github.ref, 'refs/tags/v')
      && needs.pack.outputs.files != '[]'
    needs: pack
    runs-on: ubuntu-latest
    concurrency:
      group: publish-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      id-token: write
    environment: npm
    steps:
      - uses: danielroe/uppt/publish@775bb233d2c5671b2c12d48f822778aae8231376 # v0.6.7
        with:
          files: ${{ needs.pack.outputs.files }}
